blue:
- h:
  - 106
  - 173
  s:
  - 79
  - 255
  v:
  - 29
  - 255
green:
- h:
  - 39
  - 86
  s:
  - 45
  - 255
  v:
  - 59
  - 255
red:
- h:
  - 0
  - 19
  s:
  - 42
  - 255
  v:
  - 20
  - 255
- h:
  - 136
  - 179
  s:
  - 42
  - 255
  v:
  - 20
  - 255
