string[] joint_names
float64[] positions
float32 velocity_scale
---
bool success
string message
string plan_id
float64 duration
uint32 point_count
string[] invalid_joints
string[] trajectory_joint_names
float64[] trajectory_positions
float64[] trajectory_times
